spring:
  application:
    name: consumer-app
  kafka:
    consumer:
      auto-offset-reset: latest
#      group-id: consumer-group
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    bootstrap-servers: localhost:9092
    group-id: consumer-group
    topic:
      name: test-topic
server:
  port: 8081
